Feature library tests
smileidentity/smile-identity-core-python-2 pull request #1
Opened 2020-06-30 12:51 UTC by JNdhlovu

2020-06-30 14:59 UTC, duwizerak requested changes

2020-06-30 14:59 UTC, duwizerak commented on src/IDApi.py
>              "sec_key": self.sec_key,
Tested if the code runs? colon usually is not used in input params setting in python.

2020-06-30 14:59 UTC, duwizerak commented on src/IDApi.py
>          if sid_server in [0, 1]:
I would suggest you pass in [0,1] in params instead of hardcoding them so that it's dynamic in case they may change in the future.

2020-06-30 14:59 UTC, duwizerak commented on src/IDApi.py
>              sid_server_map = {
could you instead put this in config? Cuz they are subject to change.

2020-06-30 14:59 UTC, duwizerak commented on src/IDApi.py
>              "sec_key": self.sec_key,
Also if you don't intend to use configure_json outside, make it a private method.

2020-06-30 14:59 UTC, duwizerak commented on src/IDApi.py
> +        data = json.dumps(payload)
same thing if you don't plan to execute_http outside of the class make it a private method

2020-06-30 14:59 UTC, duwizerak commented on src/IDParameters.py
> +    def get_required_params(self):
I don't see the reason of this method when it's only returning a simple list. Normally a method like this called on init, is usually used when there are some preprocessing needed. For this particular case I suggest to set them directly, also it would be good to pass them as a variable unless they are not subject to change.

2020-06-30 14:59 UTC, duwizerak commented on src/Options.py
>      def get_params(self):
This is duplication. self.option is already declared in init and could be accessed in each method and outside the class, why another method returning self.options?

2020-06-30 14:59 UTC, duwizerak commented on src/PartnerParameters.py
>      def get_params(self):
This is duplication. self.partner_params is already declared in init and could be accessed in each method and outside the class, why another method returning self.options?

2020-06-30 14:59 UTC, duwizerak commented on src/SIDServer.py
>  class SIDServer(Enum):
Why is this a class? Are you using it?

2020-06-30 14:59 UTC, duwizerak commented on src/Signature.py
> +    def __init__(self, partner_id, api_key) -> None:
Tested if this runs? the arrow key looks like a syntax error. It would good if you setup a little unit test or do a few run test, they will minimize syntax error.

2020-06-30 14:59 UTC, duwizerak commented on src/Signature.py
> +    def get_hash(self, timestamp):
If you don't expect to use it outside make it a private method.

2020-06-30 14:59 UTC, duwizerak commented on src/Signature.py
> +    def confirm_sec_key(self, timestamp, sec_key):
If you don't expect to use it outside make it a private method.

2020-06-30 14:59 UTC, duwizerak commented on src/Utilities.py
>          if sid_server in [0, 1]:
pass [0, 1] as a var, better than hardcoding if it's subject to change in future. Or put it in config.

2020-06-30 14:59 UTC, duwizerak commented on src/Utilities.py
>              sid_server_map = {
put this in config and pass url as a var, better than having it hardcoded or changing the production code all the time when the urls change or increase.

2020-06-30 14:59 UTC, duwizerak commented on src/Utilities.py
>          job_status = self.execute(self.url + "/job_status", self.configure_job_query(user_id, job_id, option_params))
This may not work. you are calling a static method using self.

2020-06-30 14:59 UTC, duwizerak commented on src/Utilities.py
>      def execute(url, payload):
This is a static method but you use it in the call as instance method.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
>                     id_info_params: IDParameters, options_params: Options):
Does this work? Unless you have a customized interpreter by default using colons to setup parameters throw an error in python.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
>          if job_type == 5:
would be good to pass 5 as a var instead of hardcoding it.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +            raise Exception("Failed to post entity to {}, response={}:{} - {}", self.url + "upload",
Let's discuss this. Not sure if it's throwing the error it's a good way of addressing it.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +            raise Exception("Failed to post entity to {}, response={}:{} - {}", self.url + "upload",
Especially if it's going to be in production.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_id_info_params(id_params: IDParameters):
this looks like a syntax error (I see repetitive use of colon in setting up parameters?)

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_partner_params(partner_params: PartnerParameters):
Repetitive colon syntax error. Did test if the code runs? Also you are calling this method as an instance variable when you declared as a static method. It will give an error.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_id_info_params(id_params: IDParameters):
Static method is called as an instance method

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> -    def validate_enrol_with_id(images_params: ImageParameters, id_info_params: IDParameters):
Repetitive colon syntax error?
Static method is called as an instance method

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_images(images_params: ImageParameters):
Repetitive colon syntax error?

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_images(images_params: ImageParameters):
non-instance method is called as an instance method

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def validate_options(self, options_params: Options):
Repetitive colon syntax error?

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
>                  "sec_key": self.sec_key,
Would suggest this is in the config file or args rather hardcoding the fields or the structure in code.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +            if image["image"].lower().endswith(('.png', '.jpg', '.jpeg')):
would suggest the extension are passed in as var rather than hardcoding them. 
We don't support .tiff?

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def execute_http(url, payload):
This static method is called as an instance method in this class, it will throw an error.

2020-06-30 14:59 UTC, duwizerak commented on src/WebApi.py
> +    def upload(url, file):
static method called as an instance method?

2020-06-30 14:59 UTC, duwizerak commented on tests/__init__.py
> +sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
could you use init and import outside classes as packages, instead of using system.path.append?

2020-06-30 15:02 UTC, duwizerak commented
@JNdhlovu thanks for the good work, just closed the first round review of your PR.
I have identified a couple of things to change. Changes suggested range from minor changes to a few major changes and syntax errors review.

Cc: @bbares , @beaglebets , @anandnagar

2020-06-30 16:03 UTC, JNdhlovu commented on src/IDApi.py
>              sid_server_map = {
@duwizerak these are hardcoded in the other libraries as well and you can pass in the URL as well if there is a change

2020-06-30 16:03 UTC, JNdhlovu commented on src/IDApi.py
>          if sid_server in [0, 1]:
@duwizerak  these are hardcoded in the other libraries as well and you can pass in the URL as well if there is a change

2020-06-30 16:04 UTC, JNdhlovu commented on src/IDApi.py
>              "sec_key": self.sec_key,
@duwizerak the colon issue you mentioned is running on python 3.7 and 3.8 is this affected by python versions

2020-06-30 16:05 UTC, JNdhlovu commented
> @JNdhlovu thanks for the good work, just closed the first round review of your PR.
> I have identified a couple of things to change. Changes suggested range from minor changes to a few major changes and syntax errors review.
> 
> Cc: @bbares , @beaglebets , @anandnagar

Thanks @duwizerak I attended to most of the issues you picked up and left a few questions to some

2020-06-30 17:38 UTC, beaglebets requested changes

2020-06-30 17:38 UTC, beaglebets commented on .gitignore
> +*.zip
There shouldn't be a zip file left behind. This is effectively a memory leak. It should either be done in memory, or if written to disk, erased afterwards. It is far more preferable to zip in memory

2020-06-30 17:38 UTC, beaglebets commented on .gitignore
> +*.zip
So I actually recommend deleting this line, as keeping it in, you would lose the warning that zips are sticking around.

2020-06-30 17:38 UTC, beaglebets commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
I think this file should be gitignored, given that is specific to an editor

2020-06-30 17:38 UTC, beaglebets commented on src/IDParameters.py
> +        required_fields = IDParameters.get_required_params()
We should do this properly and get it from the services endpoint we have.

2020-06-30 17:38 UTC, beaglebets commented on src/IDParameters.py
>      def __init__(self, first_name, middle_name, last_name, country, id_type, id_number, dob, phone_number, entered):
Since python is not a staticly typed language why isn't the input and options hash? It would bu much easier to use and we wouldn't have to upgrade the library when a field was added.

2020-06-30 17:38 UTC, beaglebets commented on src/IdApi.py
> +    timestamp = 0
These shouldn't be class attributes. This isn't threadsafe. I wouldn't instantiate a new class for each call, I would instantiate the class at startup and call submit_job later. The signature details should be specific to the job they were created for

2020-06-30 17:38 UTC, beaglebets commented on src/Utilities.py
>              sid_server_map = {
Disagree, the point behind this is all a partner needs to know is 0 for sandbox, 1 for prod. These urls shouldn't change. If they do, we have bigger issues on our hands

2020-06-30 17:38 UTC, beaglebets commented on src/Utilities.py
>          if sid_server in [0, 1]:
This is fine the way it is. Again, this is by design and all the other libraries do it. It is hardcoded so our partners don't need to know the details

2020-06-30 17:38 UTC, beaglebets commented on src/Utilities.py
> +    def get_job_status(self, user_id, job_id, option_params: Options):
Is it correct that you are passing in the class here?

2020-06-30 17:38 UTC, beaglebets commented on src/WebApi.py
> +        self.partner_id = partner_id
Again, I wouldn't put anything job specific in the class instance. I would maintain all that in the function call, so the job options, sec_key, etc... wouldn't be in the class init.

2020-06-30 17:38 UTC, beaglebets commented on src/WebApi.py
> +            id_info_params = IDParameters(None, None, None, None, None,
less than ideal formatting here. Again, passing in an options dict would solve this problem in addition to be ing more extensible

2020-06-30 17:38 UTC, beaglebets commented on src/WebApi.py
>          if job_type == 5:
this is a curious comment. The var passed in is `job_type` we are evaluating in a specific way that will not change. It is essential to the functionality that this is hard coded

2020-06-30 17:38 UTC, beaglebets commented on src/WebApi.py
> +            raise Exception("Failed to post entity to {}, response={}:{} - {}", self.url + "upload",
how would you address it? Throwing makes sense because no further execution is possible. You need to return the error that caused the call to fail. Bear in mind that most errors here are in development, or because their user did something weird. In both cases it is important to return the pertinent information. Anyone who is incorporating this into their server should have handled errors returned by the library.

2020-06-30 17:38 UTC, beaglebets commented on src/WebApi.py
> +    def validate_enrol_with_id(id_info_params: IDParameters):
You have this method in a bunch of places, probably should be in one location

2020-06-30 18:31 UTC, duwizerak commented on src/Utilities.py
>              sid_server_map = {
If they are not subject to change or same code snippet won't be used somewhere else with different urls. That's okay.

2020-06-30 18:37 UTC, duwizerak commented on src/WebApi.py
>          if job_type == 5:
If job_type naming won't change or same processing won't be needed for other jobs, that's okay.

2020-07-02 18:50 UTC, beaglebets approved these changes

2020-07-02 18:52 UTC, beaglebets commented on src/Utilities.py
>      def execute(url, payload):
It can is not used as an instance method because it doesn't require any knowledge of the instance because the url is passed in.

2020-07-02 18:54 UTC, beaglebets commented on src/Signature.py
> +    def __init__(self, partner_id, api_key) -> None:
The arrow is a form of code documentation. It indicates what is returned by the function. It is odd to have only done it on one function and we can probably remove this. Also, None is not correct since it returns the instance of itself.

2020-07-03 10:09 UTC, merged